Repository witherview/witherview_frontend, pull requests merged in 2021-04, with the labels that each got.

#20 [feature/#17] ISSUE_TEMPLATE 및 PR_TEMPLATE 을 추가한다
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PR_TEMPLATE/default.md
Labels: ⚙ environment, 🥢 chore

#22 [refactor/#21] sourcemap에 맞춰 Webpack error log 가 나오도록 설정한다
  webpack.config.js
Labels: 🛠 fix

#27 [refactor/#26] npm -> yarn으로 변경한다
  package-lock.json
  yarn.lock
Labels: refactor

#28 PR 템플릿 활성화를 위해 네이밍 문제를 해결한다
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hotfix, 🚑 bug

#10 달력 컴포넌트를 제작한다
  package.json
  src/components/organisms/Calendar/Calendar.jsx
  src/components/organisms/Calendar/Calendar.stories.js
  src/components/organisms/Calendar/CalendarItem.jsx
  src/components/organisms/Calendar/Layout.jsx
  src/components/organisms/Calendar/index.js
  src/components/organisms/index.js
  yarn.lock
Labels: 🏁 feature

#36 화면 비율 안내 메세지를 수정한다
  src/pages/FragileRatioPage/FragileRatioPage.js
Labels: 🪛 refactor

#31 TypeScript 작업 병행을 위한 환경 설정을 한다
  .babelrc
  .eslintrc.js
  package.json
  src/index.tsx
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: ⚙ environment, 🥢 chore

#16 actions workflow 새 organization에 맞게 migrate한다
  .github/workflows/storybook.yml
Labels: 📍 review request, 🛠 fix

#32 사이드바 디자인 변경 및 트랜지션을 추가한다
  src/App.js
  src/components/organisms/Modal/QuestionListSaveModal/QuestionListSaveModal.js
  src/components/organisms/QuestionCardView/QuestionCardView.js
  src/components/organisms/Sidebar/SideBar.js
  src/components/organisms/Sidebar/SidebarButton/SideBarButton.js
  src/components/organisms/StudyCardView/StudyCardView.js
  src/pages/MyVideoPage/MyVideoPage.js
  src/pages/QuestionListPage/IsQuestionList/IsQuestionList.js
  src/pages/QuestionListPage/NoList/NoList.js
  src/pages/SelfStudyChecklistPage/SelfStudyChecklistPage.js
  src/pages/SelfTrainEntryPage/SelfTrainEntryPage.js
  src/pages/SelfTrainPage/SelfTrainPage.js
  src/pages/SelfTrainSettingPage/SelfTrainSettingPage.js
Labels: 📍 review request, 🪛 refactor

#12 dropdown 활성화 후 다른 영역 클릭시 비활성화 하도록 한다
  src/components/organisms/Modal/StudyMakeModal/StudyMakeModal.js
  src/pages/SignUpPage/SignUpPage.js
Labels: 📍 review request, 🛠 fix

#13 Session 기반 인증 JWT 기준으로 변경 및 테스트한다
  .eslintrc.js
  src/App.js
  src/components/atoms/ProfileIcon/ProfileIcon.js
  src/components/molecules/ProfileEdit/ProfileEdit.js
  src/components/organisms/Modal/EvaluationModal/EvaluationModal.js
  src/components/organisms/Modal/QuestionListSaveModal/QuestionListSaveModal.js
  src/components/organisms/Modal/StudyMakeModal/StudyMakeModal.js
  src/components/organisms/QuestionCardView/QuestionCardView.js
  src/components/organisms/StudyCardView/StudyCardView.js
  src/context/serverContext.js
  src/mocks/QuestionItemMock.js
  src/mocks/QuestionListMock.js
  src/mocks/QuestionMock.js
  src/pages/LoginPage/LoginPage.js
  src/pages/MyPage/MyPage.js
  src/pages/MyVideoPage/MyVideoPage.js
  src/pages/PeerStudyMainPage/PeerStudyMainPage.js
  src/pages/PeerStudyRoomPage/PeerStudyRoomPage.js
  src/pages/QuestionListPage/IsQuestionList/IsQuestionList.js
  src/pages/QuestionListPage/QuestionListPage.js
  src/pages/QuestionPage/QuestionPage.js
  src/pages/SelfStudyChecklistPage/SelfStudyChecklistPage.js
  src/pages/SelfTrainPage/SelfTrainPage.js
  src/pages/SelfTrainSettingPage/SelfTrainSettingPage.js
  src/pages/SignUpPage/SignUpPage.js
  src/pages/VideoPage/VideoPage.js
  src/pages/WelcomePage/WelcomePage.js
  src/repository/accountRepository.js
  src/repository/chattingRepository.js
  src/repository/groupRepository.js
  src/repository/interviewStudyRepository.js
  src/repository/loginRepository.js
  src/repository/questionListRepository.js
  src/repository/sampleRepository.js
  src/repository/selfCheckListRepository.js
  src/repository/selfHistoryRepository.js
  src/repository/signUpRepository.js
  src/repository/studyHistoryRepository.js
  src/routes/AuthRoute/AuthRoute.js
  src/store/Auth/auth.js
  src/utils/constant.js
Labels: 📍 review request, 🪛 refactor

#6 프로필사진 업데이트 및 닉네임 변경 로직을 추가한다
  src/components/atoms/ProfileIcon/ProfileIcon.js
  src/components/molecules/ProfileEdit/ProfileEdit.js
  src/pages/LoginPage/LoginPage.js
  src/pages/WelcomePage/WelcomePage.js
  src/repository/updateProfile.js
  src/routes/AuthRoute/AuthRoute.js
  src/store/Auth/auth.js
Labels: 🏁 feature, 🔍 ing

#59 이미지 업로드 로직에 용량제한 및 형식 validation을 추가한다
  src/components/molecules/ProfileEdit/ProfileEdit.js
  src/components/organisms/Modal/QuestionListSaveModal/QuestionListSaveModal.js
Labels: 📍 review request, 🛠 fix

#55 리덕스툴킷 액션생성함수를 수정 또는 삭제한다
  src/components/organisms/Modal/EvaluationModal/EvaluationModal.js
  src/components/organisms/Modal/Modal.stories.js
  src/components/organisms/Modal/ModalWrapper/ModalWrapper.js
  src/components/organisms/Modal/QuestionListSaveModal/QuestionListSaveModal.js
  src/components/organisms/Modal/SelfTrainStartModal/SelfTrainStartModal.js
  src/components/organisms/Modal/StudyMakeModal/StudyMakeModal.js
  src/pages/PeerStudyMainPage/PeerStudyMainPage.js
  src/pages/PeerStudyTrainPage/PeerStudyTrainPage.js
  src/pages/QuestionPage/QuestionPage.js
  src/store/Group/group.js
  src/store/Modal/modal.js
  src/store/Question/question.js
Labels: 📍 review request, 🪛 refactor

#60 react-router-dom 의 path 수정 반영 못한부분을 수정한다
  src/components/organisms/Modal/QuestionListSaveModal/QuestionListSaveModal.js
  src/components/organisms/StudyCardView/StudyCardView.js
Labels: 🔥 hotfix

#63 카메라를 사용 후 사용하지 않는 화면에서도 사용중으로 표시되는 에러를 해결한다
  src/components/molecules/SmallCamView/SmallCamView.js
  src/components/organisms/CamView/CamView.js
  src/hooks/useMediaRecorder.js
  src/pages/PeerStudyTrainPage/MyCamView.js
  src/utils/snippet.js
Labels: 📍 review request, 🚑 bug, 🛠 fix

#68 EvaluationModal 수정사항 반영이 되지 않은 부분을 반영한다
  src/components/organisms/Modal/EvaluationModal/EvaluationModal.js
Labels: 📍 review request, 🔥 hotfix
