Repository witherview/witherview_frontend, pull requests merged in 2021-06, with the labels that each got.

#86 modal dispatch payload에 객체형태로 반영 안되어있던 부분을 수정한다
  src/components/organisms/QuestionCardView/QuestionCardView.js
Labels: 📍 review request, 🔥 hotfix

#83 question, questionlist 변경된 구조에 맞춰 엔드포인트를 수정한다
  src/components/organisms/QuestionCardView/QuestionCardView.js
  src/pages/QuestionListPage/IsQuestionList/IsQuestionList.js
  src/pages/QuestionPage/QuestionPage.js
  src/pages/SelfTrainEntryPage/SelfTrainEntryPage.js
  src/pages/SelfTrainPage/SelfTrainPage.js
  src/pages/SelfTrainSettingPage/SelfTrainSettingPage.js
  src/repository/questionListRepository.js
Labels: 📍 review request, 🪛 refactor

#87 혼자연습 Setting 페이지에서 발생한 이슈들(페이지 라우팅 path, 데이터 접근)을 해결한다
  src/App.js
  src/pages/SelfTrainSettingPage/SelfTrainSettingPage.js
Labels: 📍 review request, 🔥 hotfix

#89 Icon 컴포넌트 유지보수성 강화를 위해 리팩토링한다
  src/components/atoms/Icon/Icon.js
Labels: 🔍 ing, 🛠 fix

#93 변경된 마이페이지 디자인을 적용한다
  src/pages/MyPage/Box/Box.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.style.js
Labels: 🌈 style

#95 feat: 🎸 마이페이지에서 개인정보를 수정 가능하도록 api 연동한다
  .gitignore
  src/components/atoms/Icon/Icon.js
  src/components/atoms/InputBar/InputBar.js
  src/components/atoms/SubHeader/SubHeader.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.style.js
  yarn.lock
Labels: 🏁 feature

#96 이전 PR에서 지워진 yarn.lock을 복구한다
  yarn.lock
Labels: 🔥 hotfix

#97 Peer Study 채팅 연결 및 동작이 정상적으로 되도록 한다
  src/components/organisms/RoomChat/RoomChat.js
  src/hooks/useSockStomp.js
  src/routes/PeerStudyRoute/PeerStudyRoute.js
Labels: 🔥 hotfix

#103 Enter keydown 이벤트 발생시 질문이 등록되거나 채팅이 쳐지도록 한다
  src/components/molecules/ChatInput/ChatInput.js
  src/pages/QuestionPage/QuestionPage.js
Labels: 🏁 feature, 📍 review request

#90 관심 산업을 선택하는 모달 컴포넌트를 추가한다
  src/components/molecules/index.js
  src/components/organisms/Modal/IndustrySelectModal/IndustrySelectModal.js
  src/components/organisms/Modal/IndustrySelectModal/index.js
  src/components/organisms/Modal/Modal.js
  src/components/organisms/Modal/Modal.stories.js
  src/repository/groupRepository.js
  src/store/Modal/modal.js
  src/utils/constant.js
Labels: 🏁 feature

#107 산업태그 선택 모달에서 필요없는 eslint 설정을 비활성화한다
  src/components/organisms/Modal/IndustrySelectModal/IndustrySelectModal.js
Labels: 🔥 hotfix

#110 Sidebar상단 위더뷰 아이콘을 누르면 랜딩페이지로 이동한다
  src/components/organisms/Sidebar/SideBar.js
Labels: 🏁 feature

#98 Peer Study Room에 유저정보 관련 API를 연결한다
  .storybook/preview.js
  src/components/atoms/ToggleButton/ToggleButton.js
  src/components/organisms/InterviewChat/InterviewChat.js
  src/components/organisms/Modal/EvaluationModal/EvaluationModal.js
  src/components/organisms/ProfileInfoContainer/ProfileInfoContainer.js
  src/components/organisms/StudyCardView/StudyCardView.js
  src/hooks/useSockStomp.js
  src/pages/PeerStudyMainPage/PeerStudyMainPage.js
  src/pages/PeerStudyMainPage/PeerStudyMainPage.style.js
  src/pages/PeerStudyRoomPage/PeerStudyRoomPage.js
  src/pages/PeerStudyRoomPage/PeerStudyRoomPage.style.js
  src/pages/PeerStudyRoomPage/UsersSection.js
  src/pages/PeerStudySettingPage/PeerStudySettingPage.js
  src/pages/PeerStudyTrainPage/PeerStudyTrainPage.js
  src/repository/groupRepository.js
  src/repository/studyHistoryRepository.js
  src/routes/PeerStudyRoute/PeerStudyRoute.js
  src/store/Train/train.js
Labels: 📍 review request, 🪛 refactor

#111 사이드바에 텍스트를 추가한다
  src/components/organisms/Sidebar/SideBar.js
  src/components/organisms/Sidebar/SideBar.stories.js
  src/components/organisms/Sidebar/SidebarButton/SideBarButton.js
Labels: 📍 review request, 🛠 fix
