Repository witherview/witherview_frontend, pull requests merged in 2021-05, with the labels that each got.

#54 API 명세에 존재하지만 클라이언트에서는 누락된 엔드포인트를 추가한다
  src/App.js
  src/components/organisms/Modal/EvaluationModal/EvaluationModal.js
  src/components/organisms/Modal/Modal.js
  src/components/organisms/Modal/QuestionListEditModal/QuestionListEditModal.js
  src/components/organisms/Modal/QuestionListEditModal/index.js
  src/components/organisms/QuestionCardView/QuestionCardView.js
  src/mocks/EvaluationListMock.js
  src/pages/MyVideoPage/MyVideoPage.js
  src/pages/PeerStudyMainPage/PeerStudyMainPage.js
  src/pages/PeerStudyRoomPage/PeerStudyRoomPage.js
  src/pages/QuestionListPage/IsQuestionList/IsQuestionList.js
  src/pages/SelfStudyChecklistPage/index.js
  src/pages/SelfTrainChecklistPage/SelfTrainChecklistPage.js
  src/pages/SelfTrainChecklistPage/SelfTrainChecklistPage.stories.js
  src/pages/SelfTrainChecklistPage/index.js
  src/pages/SelfTrainPage/SelfTrainPage.js
  src/pages/VideoPage/VideoPage.js
  src/repository/accountRepository.js
  src/repository/chattingRepository.js
  src/repository/groupRepository.js
  src/repository/questionListRepository.js
  src/repository/selfCheckListRepository.js
  src/repository/selfHistoryRepository.js
  src/repository/studyHistoryRepository.js
  src/store/Modal/modal.js
  src/store/Time/time.js
  src/utils/constant.js
Labels: 📍 review request, 🪛 refactor

#66 체크리스트 페이지 녹화 영상 progress bar 정상화 및 구조 리팩토링한다
  src/App.js
  src/components/organisms/Modal/EvaluationModal/EvaluationModal.js
  src/components/organisms/Modal/Modal.js
  src/components/organisms/Modal/QuestionListEditModal/QuestionListEditModal.js
  src/components/organisms/Modal/QuestionListEditModal/index.js
  src/components/organisms/QuestionCardView/QuestionCardView.js
  src/mocks/EvaluationListMock.js
  src/pages/MyVideoPage/MyVideoPage.js
  src/pages/PeerStudyMainPage/PeerStudyMainPage.js
  src/pages/PeerStudyRoomPage/PeerStudyRoomPage.js
  src/pages/QuestionListPage/IsQuestionList/IsQuestionList.js
  src/pages/SelfStudyChecklistPage/index.js
  src/pages/SelfTrainChecklistPage/SelfTrainChecklistPage.js
  src/pages/SelfTrainChecklistPage/SelfTrainChecklistPage.stories.js
  src/pages/SelfTrainChecklistPage/index.js
  src/pages/SelfTrainPage/SelfTrainPage.js
  src/pages/VideoPage/VideoPage.js
  src/repository/accountRepository.js
  src/repository/chattingRepository.js
  src/repository/groupRepository.js
  src/repository/questionListRepository.js
  src/repository/selfCheckListRepository.js
  src/repository/selfHistoryRepository.js
  src/repository/studyHistoryRepository.js
  src/store/Modal/modal.js
  src/store/Time/time.js
  src/utils/constant.js
Labels: 🔍 ing, 🪛 refactor

#76 Wrapper 영역을 각 페이지별로 일치될 수 있도록 수정한다
  src/App.js
  src/components/organisms/ProfileMenuContainer/ProfileMenuContainer.js
  src/components/organisms/Sidebar/SideBar.js
  src/pages/MyPage/MyPage.style.js
  src/pages/MyVideoPage/MyVideoPage.js
  src/pages/PeerStudyMainPage/PeerStudyMainPage.style.js
  src/pages/QuestionListPage/QuestionListPage.js
  src/pages/QuestionPage/QuestionPage.js
  src/pages/SelfTrainEntryPage/SelfTrainEntryPage.js
  src/pages/SelfTrainPage/SelfTrainPage.style.js
  src/pages/SelfTrainSettingPage/SelfTrainSettingPage.js
Labels: 📍 review request, 🪛 refactor

#75 관심 산업/직무 태그 컴포넌트를 추가한다
  .storybook/webpack.config.js
  src/components/atoms/TagIcon/TagIcon.js
  src/components/atoms/TagIcon/TagIcon.stories.js
  src/components/atoms/TagIcon/index.js
  src/components/molecules/Tag/Tag.js
  src/components/molecules/Tag/Tag.stories.js
  src/components/molecules/Tag/index.js
  tsconfig.json
  webpack.config.js
Labels: 🏁 feature, 🔍 ing

#79 Quality Assurance을 진행한다
  src/components/molecules/ProfileEdit/ProfileEdit.js
  src/components/organisms/CamView/CamView.js
  src/context/serverContext.js
  src/pages/SignUpPage/SignUpPage.js
Labels: 📍 review request, 🛠 fix
