Repository witherview/witherview_frontend, pull requests merged in 2021-07, with the labels that each got.

#117 회원 탈퇴 기능을 구현한다
  src/components/organisms/Modal/Modal.js
  src/components/organisms/Modal/WithdrawConfirmModal/WithdrawConfirmModal.js
  src/components/organisms/Modal/WithdrawConfirmModal/index.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.style.js
  src/repository/accountRepository.js
  src/store/Modal/modal.js
  src/utils/constant.js
Labels: 🏁 feature

#108 로그인한 상태에서 랜딩 페이지 헤더에 사용자 정보가 나타나도록 한다
  src/components/atoms/ProfileIcon/ProfileIcon.js
  src/components/organisms/ProfileMenuContainer/ProfileMenuContainer.js
  src/pages/LandingPage/LandingHeader.js
  src/store/Auth/auth.js
Labels: 🏁 feature, 🔍 ing

#65 연습 내역 다시보기 카드뷰 컴포넌트를 제작한다
  src/App.js
  src/components/molecules/HoverDropDown/HoverDropDown.js
  src/components/molecules/HoverDropDown/index.js
  src/components/molecules/index.js
  src/components/organisms/ReplayCardView/ReplayCardView.js
  src/components/organisms/ReplayCardView/ReplayCardView.stories.js
  src/components/organisms/ReplayCardView/index.js
  src/pages/MyVideoPage/MyVideoPage.js
Labels: 🏁 feature, 📍 review request

#119 이메일 비밀번호 찾기 기능 구현한다
  .storybook/manager.js
  .storybook/preview.js
  src/App.js
  src/pages/LoginPage/LoginPage.js
  src/pages/PasswordPage/PasswordPage.js
  src/pages/PasswordPage/PasswordPage.stories.js
  src/pages/PasswordPage/index.js
  src/repository/accountRepository.js
Labels: 🏁 feature
