Repository witherview/witherview_frontend, pull requests merged in 2021-08, with the labels that each got.

#3 시그널링 서버 disconnect 로직 및 client에서 동작가능하도록 하는 로직을 추가한다
  __mock-server/.gitignore
  __mock-server/server.js
  src/hooks/useSocketSignal.js
  src/pages/PeerStudyTrainPage/PeerStudyTrainPage.js
  src/pages/PeerStudyTrainPage/PeerVideo.js
  webpack.config.js
Labels: 🪛 refactor, 📍 review request

#81 Input에 대한 Validation 을 추가한다
  .eslintrc.js
  .gitignore
  src/components/atoms/InputBar/InputBar.stories.js
  src/components/atoms/Validation/Validation.js
  src/components/atoms/Validation/Validation.stories.js
  src/components/atoms/Validation/index.js
  src/components/atoms/index.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.style.js
  src/pages/SelfTrainSettingPage/SelfTrainSettingPage.js
  src/pages/SignUpPage/SignUpPage.js
Labels: 🏁 feature

#123 404 접근시에 3초 후 첫화면으로 Redirect한다
  src/App.js
  src/components/organisms/Sidebar/SideBar.js
  src/pages/404.js
  src/routes/AuthRoute/AuthRoute.js
Labels: 🏁 feature

#125 Feature/#122 회원 탈퇴 기획 디자인 변경을 적용한다.
  src/App.js
  src/assets/images/icons.png
  src/components/atoms/Icon/Icon.js
  src/components/organisms/Modal/AlertModal/AlertModal.js
  src/components/organisms/Modal/AlertModal/index.js
  src/components/organisms/Modal/Modal.js
  src/components/organisms/Modal/Modal.stories.js
  src/components/organisms/Modal/WithdrawConfirmModal/WithdrawConfirmModal.js
  src/components/organisms/Modal/WithdrawConfirmModal/index.js
  src/pages/MyPage/MyPage.js
  src/pages/WithdrawPage/WithdrawPage.js
  src/pages/WithdrawPage/WithdrawPage.stories.js
  src/pages/WithdrawPage/WithdrawStep/One.js
  src/pages/WithdrawPage/WithdrawStep/Two.js
  src/pages/WithdrawPage/index.js
  src/utils/constant.js
Labels: 🪛 refactor

#126 랜딩페이지 UI를 업데이트한다
  src/components/atoms/Button/Button.js
  src/components/atoms/TextButton/TextButton.js
  src/hooks/useSocketSignal.js
  src/pages/LandingPage/LandingBottom.js
  src/pages/LandingPage/LandingHeader.js
  src/pages/LandingPage/LandingMiddleOne.js
  src/pages/LandingPage/LandingMiddleThree.js
  src/pages/LandingPage/LandingMiddleTwo.js
  src/pages/LandingPage/LandingTop.js
  src/pages/LandingPage/components/TextButtonProps.js
Labels: 🪛 refactor

#121 스터디룸 만들기 모달 UI를 업데이트한다
  package.json
  src/components/organisms/Modal/StudyMakeModal/StudyMakeModal.js
  yarn.lock
Labels: 🪛 refactor
